# Generated by Django 5.2.8 on 2025-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat', models.FloatField()),
                ('tinggi', models.FloatField()),
                ('bmi', models.FloatField()),
                ('kategori', models.CharField(max_length=50)),
                ('riwayat_input', models.TextField()),
                ('penyakit_terdeteksi', models.TextField()),
                ('rekomendasi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
