# Generated by Django 5.2.8 on 2026-01-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mentalhealthlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymealplan',
            old_name='alergi_makanan',
            new_name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='kondisi_kesehatan',
        ),
    ]
