# Generated by Django 5.2.8 on 2026-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmiresult',
            name='usia',
            field=models.IntegerField(default=0),
        ),
    ]
