# Generated by Django 5.2.8 on 2026-02-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bmiresult_usia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmiresult',
            name='gender',
            field=models.CharField(default='Laki-laki', max_length=20),
        ),
    ]
